services:
  postgres-db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ~/.docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: somePasswordSecured
      PGDATA: /var/lib/postgresql/data/pgdata
